// Word packs for 30 Seconds game
// Each country has words organized by age group

const wordPacks = {
  worldwide: { name: "Worldwide", flag: "🌍", ages: {
    kids: ["Dog","Cat","Lion","Elephant","Giraffe","Monkey","Penguin","Dolphin","Tiger","Bear","Rabbit","Butterfly","Dinosaur","Shark","Horse","Cow","Pig","Duck","Frog","Turtle","Zebra","Kangaroo","Panda","Koala","Owl","Bee","Whale","Mickey Mouse","SpongeBob","Elsa","Peppa Pig","Paw Patrol","Bluey","Pikachu","Mario","Sonic","Dora","Minions","Shrek","Nemo","Simba","Buzz Lightyear","Woody","Olaf","Baby Shark","Hello Kitty","Winnie the Pooh","Spider-Man","Batman","Princess","Unicorn","Mermaid","Dragon","Moana","Lightning McQueen","Pizza","Ice Cream","Hamburger","Hot Dog","French Fries","Chocolate","Cake","Cookies","Banana","Apple","Watermelon","Popcorn","Pancakes","Candy","Donut","Dancing","Singing","Swimming","Running","Jumping","Sleeping","Eating","Laughing","Playing","Drawing","Beach","Playground","Zoo","School","Park","Birthday Party","Christmas","Halloween","Rainbow","Sun","Moon","Star","Mommy","Daddy","Baby","Teacher","Doctor","Firefighter","Santa Claus","Pirate"],
    tweens: ["Minecraft","Roblox","Fortnite","Pokemon","Mario Kart","Zelda","Among Us","FIFA","Nintendo Switch","PlayStation","Xbox","MrBeast","PewDiePie","Dream","Ninja","TikTok","YouTube","Instagram","Snapchat","Harry Potter","Marvel","Spider-Man","Avengers","Stranger Things","Wednesday","Star Wars","Baby Yoda","Taylor Swift","Olivia Rodrigo","BTS","Billie Eilish","Ed Sheeran","Cristiano Ronaldo","Lionel Messi","LeBron James","Stephen Curry","Simone Biles","Olympics","World Cup","Super Bowl","Pizza","Tacos","Sushi","Boba Tea","Doritos","Oreos","McDonalds","Starbucks","iPhone","AirPods","Selfie","Netflix","Disney Plus","Homework","Sleepover","Summer Camp"],
    teens: ["TikTok","Instagram","Snapchat","BeReal","Discord","Influencer","Going Viral","FYP","Rizz","GOAT","No Cap","Taylor Swift","Drake","Kendrick Lamar","Travis Scott","Doja Cat","SZA","The Weeknd","Bad Bunny","Billie Eilish","BTS","Blackpink","Coachella","Eras Tour","Netflix","Euphoria","Wednesday","Outer Banks","Anime","Demon Slayer","Fortnite","Valorant","Call of Duty","GTA","Twitch","Streaming","Esports","LeBron James","Steph Curry","Patrick Mahomes","Messi","Ronaldo","Mbappé","March Madness","Prom","Homecoming","SAT","College Applications","Driver's License","Thrifting","Vintage","Streetwear","Nike Dunks","Jordans","Chipotle","Boba Tea","Crumbl Cookies","Situationship","Red Flag","Ghosting","Mental Health"],
    adults: ["Beyoncé","Taylor Swift","Rihanna","Lady Gaga","Drake","Post Malone","The Weeknd","Leonardo DiCaprio","Margot Robbie","Zendaya","Dwayne Johnson","Chris Hemsworth","Game of Thrones","Breaking Bad","The Office","Friends","Succession","The Bear","Ted Lasso","Love Island","Marvel","Barbie","Oppenheimer","John Wick","Top Gun","Mortgage","Student Loans","401k","Adulting","Work From Home","Zoom","LinkedIn","Side Hustle","Sunday Scaries","Brunch","Tinder","Bumble","Dating App","Ghosting","Red Flag","Apple","Tesla","Netflix","Uber","DoorDash","Starbucks","Target","Amazon Prime","CrossFit","Peloton","Yoga","Marathon","Vegas Trip","Bachelorette Party"],
    over40: ["Michael Jackson","Madonna","Prince","Whitney Houston","The Beatles","Queen","Elton John","David Bowie","Fleetwood Mac","ABBA","U2","Bon Jovi","Nirvana","Spice Girls","Titanic","Pretty Woman","Forrest Gump","E.T.","Indiana Jones","Back to the Future","Ghostbusters","Die Hard","Seinfeld","Friends","Cheers","The Sopranos","Tom Hanks","Meryl Streep","Tom Cruise","Julia Roberts","Brad Pitt","George Clooney","Harrison Ford","Oprah","Fall of Berlin Wall","Princess Diana","Y2K","Moon Landing","First iPhone","Walkman","VHS","Blockbuster","Cassette Tape","AOL","Dial Up","MySpace","Game Boy","Pac-Man","Tetris","Michael Jordan","Magic Johnson","Muhammad Ali","Tiger Woods","Wayne Gretzky","Mustang","Corvette","Volkswagen Beetle"],
    allAges: ["Dog","Cat","Lion","Elephant","Penguin","Dolphin","Panda","Whale","Pizza","Ice Cream","Hamburger","Chocolate","Cake","Coffee","Banana","Eiffel Tower","Statue of Liberty","Great Wall of China","Pyramids","Big Ben","Taj Mahal","Grand Canyon","Mickey Mouse","Spider-Man","Batman","Santa Claus","Harry Potter","James Bond","Michael Jackson","Elvis Presley","The Beatles","Taylor Swift","Beyoncé","Tom Hanks","Dwayne Johnson","Leonardo DiCaprio","Football","Basketball","Tennis","Swimming","Olympics","World Cup","Michael Jordan","Usain Bolt","Serena Williams","Cristiano Ronaldo","Lionel Messi","Apple","Google","McDonald's","Coca-Cola","Disney","Nike","Netflix","The Lion King","Toy Story","Frozen","Star Wars","Titanic","Dancing","Singing","Running","Laughing","Television","Computer","Bicycle","Airplane","Umbrella"]
  }},
  southAfrica: { name: "South Africa", flag: "🇿🇦", ages: {
    kids: ["Simba Chips","Oros","Flings","Ghost Pops","Milo","Ouma Rusks","Lion","Elephant","Giraffe","Zebra","Hippo","Rhino","Meerkat","Springbok","Table Mountain","Beach","Zoo","Kruger Park","Safari","Braai","Boerewors Roll","Vetkoek","Koeksister","Melktart","Soccer","Rugby Ball","Swimming","Cricket","Springboks","Bafana Bafana","Kaizer Chiefs","Orlando Pirates","Checkers","Pick n Pay","Spur","Wimpy","Taxi","Bakkie","Robot","Beach Holiday","Game Drive","Takalani Sesame","Dancing","Singing","Playing","Teacher","Doctor","Firefighter","Farmer","Rainbow","Sun"],
    tweens: ["Siya Kolisi","Springboks","Cheslin Kolbe","Eben Etzebeth","Faf de Klerk","Bafana Bafana","Kaizer Chiefs","Orlando Pirates","Mamelodi Sundowns","Takealot","Mr D","Uber","DSTV","TikTok","YouTube","WhatsApp","Minecraft","Fortnite","Roblox","FIFA","PlayStation","Xbox","Table Mountain","Kruger Park","Sun City","Durban Beach","Cape Town","Gold Reef City","uShaka Marine World","Simba Chips","Biltong","Boerewors","Bunny Chow","Gatsby","Steers","Spur","Nando's","KFC","McDonald's","Vodacom","MTN","Load Shedding","Eskom","Heritage Day","Youth Day","Braai Day"],
    teens: ["Siya Kolisi","Cheslin Kolbe","Rassie Erasmus","Springboks","Dricus du Plessis","Trevor Noah","Black Coffee","Cassper Nyovest","Nasty C","AKA","Amapiano","Gqom","Uncle Waffles","DBN Gogo","Kabza De Small","DJ Maphorisa","TikTok","Instagram","Twitter","YouTube","BeReal","Netflix","Showmax","DSTV","Blood & Water","The Wife","Takealot","Shein","Mr Price","Superbalist","Matric Dance","Rage","University","NSFAS","Uber","Bolt","Mr D","Checkers Sixty60","Load Shedding","Eskom","Braai","Shisa Nyama","Bunny Chow","Castle","Savanna","Table Mountain","Lion's Head","Camps Bay"],
    adults: ["Siya Kolisi","Rassie Erasmus","Springboks World Cup","AB de Villiers","Dricus du Plessis","Trevor Noah","Charlize Theron","Elon Musk","Black Coffee","Cyril Ramaphosa","Nelson Mandela","Desmond Tutu","Julius Malema","Load Shedding","Eskom","Stage 6","Water Crisis","E-tolls","Home Affairs Queue","Biltong","Boerewors","Braai","Potjiekos","Bunny Chow","Bobotie","Castle Lager","Savanna","Amarula","Pinotage","Table Mountain","Kruger National Park","Cape Winelands","Garden Route","V&A Waterfront","Sandton City","Discovery","Old Mutual","FNB","Vodacom","DSTV","Comrades Marathon","Two Oceans","Cape Town Cycle Tour"],
    over40: ["Nelson Mandela","Desmond Tutu","FW de Klerk","Thabo Mbeki","1995 Rugby World Cup","Francois Pienaar","Joel Stransky","Chester Williams","Gary Player","Ernie Els","Johnny Clegg","Miriam Makeba","Hugh Masekela","Brenda Fassie","Lucky Dube","Ladysmith Black Mambazo","Charlize Theron","Leon Schuster","The Gods Must Be Crazy","Tsotsi","Egoli","7de Laan","Generations","SABC","M-Net","Apartheid","1994 Elections","Freedom Day","Robben Island","Biltong","Boerewors","Mrs Balls Chutney","Ouma Rusks","Rooibos","Castle Lager","Lion Lager","Brandy and Coke","Amarula","Combi","Citi Golf","OK Bazaars","Edgars","Springbok Radio"],
    allAges: ["Siya Kolisi","Springboks","Rugby World Cup","Table Mountain","Kruger Park","Nelson Mandela","Robben Island","Cape Town","Johannesburg","Durban","Biltong","Boerewors","Braai","Bunny Chow","Koeksister","Melktart","Simba Chips","Ouma Rusks","Rooibos Tea","Amarula","Castle Lager","Lion","Elephant","Rhino","Leopard","Springbok","Meerkat","Checkers","Pick n Pay","Woolworths","Nando's","Steers","Taxi Rank","Bakkie","Robot","Braai Day","Heritage Day","Load Shedding","Ubuntu","Lekker","Eish","Now Now","Howzit","Kaizer Chiefs","Orlando Pirates","Comrades Marathon","Trevor Noah","Charlize Theron","Black Coffee","Freedom Day"]
  }},
  usa: { name: "USA", flag: "🇺🇸", ages: {
    kids: ["Mickey Mouse","SpongeBob","Paw Patrol","Bluey","Elsa","Moana","Toy Story","Finding Nemo","Pikachu","Mario","Sonic","Spider-Man","Batman","Superman","Captain America","Hot Dog","Hamburger","Pizza","Mac and Cheese","Chicken Nuggets","French Fries","Ice Cream","Cookies","Disney World","Disneyland","Beach","Playground","Zoo","Statue of Liberty","Grand Canyon","Baseball","Football","Basketball","Soccer","Swimming","Fourth of July","Halloween","Thanksgiving","Christmas","Easter","School Bus","Fire Truck","Teacher","Doctor","Firefighter","Astronaut","Dog","Cat","Goldfish","Birthday Party","Sleepover","Summer Camp"],
    tweens: ["MrBeast","Dream","Ninja","Minecraft","Fortnite","Roblox","Among Us","FIFA","TikTok","YouTube","Instagram","Snapchat","Discord","Taylor Swift","Olivia Rodrigo","Billie Eilish","BTS","Drake","Stranger Things","Wednesday","Marvel","Spider-Man","Avengers","Star Wars","Baby Yoda","LeBron James","Stephen Curry","Patrick Mahomes","Super Bowl","NBA Finals","Pizza","Tacos","Chipotle","Starbucks","Boba Tea","Doritos","Oreos","Disney World","Universal Studios","Times Square","Hollywood","iPhone","AirPods","Netflix","Disney Plus","Homework","Summer Break"],
    teens: ["TikTok","Instagram","Snapchat","BeReal","Discord","Influencer","Going Viral","FYP","Taylor Swift","Drake","Kendrick Lamar","Travis Scott","Doja Cat","Olivia Rodrigo","The Weeknd","Coachella","Lollapalooza","Eras Tour","Netflix","Euphoria","Wednesday","Outer Banks","Anime","Demon Slayer","Fortnite","Valorant","Call of Duty","GTA","Twitch","Streaming","Patrick Mahomes","LeBron James","Steph Curry","March Madness","Super Bowl","Prom","Homecoming","SAT","College Applications","Driver's License","Thrifting","Vintage","Nike Dunks","Jordans","Stanley Cup","Chipotle","Boba Tea","Crumbl Cookies","Situationship","Red Flag","Ghosting","Rizz"],
    adults: ["Taylor Swift","Beyoncé","Rihanna","Lady Gaga","Drake","The Weeknd","Leonardo DiCaprio","Margot Robbie","Zendaya","Dwayne Johnson","Chris Hemsworth","Game of Thrones","Breaking Bad","The Office","Friends","Succession","Ted Lasso","Marvel","Barbie","Oppenheimer","John Wick","Top Gun","Super Bowl","NBA Finals","World Series","Tom Brady","LeBron James","Michael Jordan","Mortgage","Student Loans","401k","Adulting","Work From Home","Zoom","Side Hustle","Tinder","Bumble","Hinge","Dating App","Ghosting","Brunch","Happy Hour","Apple","Tesla","Amazon","Netflix","Uber","Starbucks","Target","CrossFit","Peloton","Yoga","Vegas Trip","Bachelorette Party"],
    over40: ["Michael Jackson","Madonna","Prince","Whitney Houston","The Beatles","Queen","Elton John","Bruce Springsteen","Billy Joel","Bon Jovi","Nirvana","Pearl Jam","Tom Hanks","Meryl Streep","Tom Cruise","Julia Roberts","Brad Pitt","George Clooney","Titanic","Pretty Woman","Forrest Gump","Top Gun","Die Hard","E.T.","Back to the Future","Seinfeld","Friends","Cheers","The Sopranos","Saturday Night Live","Michael Jordan","Magic Johnson","Muhammad Ali","Tiger Woods","Derek Jeter","9/11","Moon Landing","Y2K","Reagan","Clinton","Obama","Oprah","Walkman","VHS","Blockbuster","AOL","Dial Up","Game Boy","Pac-Man","Mustang","Corvette","Camaro","Jeopardy","Wheel of Fortune"],
    allAges: ["Statue of Liberty","Grand Canyon","Disney World","Hollywood","Times Square","Las Vegas","Hot Dog","Hamburger","Pizza","Apple Pie","Mac and Cheese","Coca-Cola","Thanksgiving Turkey","Super Bowl","Fourth of July","Halloween","Thanksgiving","NBA","NFL","Michael Jordan","LeBron James","Tom Brady","Serena Williams","Taylor Swift","Beyoncé","Michael Jackson","Elvis Presley","Mickey Mouse","Spider-Man","Superman","Batman","Captain America","Tom Hanks","Dwayne Johnson","Oprah","Apple","Google","Amazon","Disney","McDonald's","Nike","Starbucks","Baseball","Football","Basketball","American Dream","Road Trip","National Parks"]
  }},
  uk: { name: "UK", flag: "🇬🇧", ages: {
    kids: ["Peppa Pig","Bluey","Hey Duggee","Paddington Bear","Thomas the Tank Engine","Postman Pat","Fireman Sam","Mr Bean","Wallace and Gromit","Harry Potter","Hogwarts","Fish and Chips","Crumpets","Jelly","Beans on Toast","Jaffa Cakes","Smarties","Buckingham Palace","Big Ben","London Eye","Tower of London","Red Bus","Black Cab","Underground","Red Phone Box","Queen","King","Prince","Princess","Castle","Royal Guard","Corgi","Football","Cricket","Swimming","Tennis","Christmas","Easter","Bonfire Night","School","Teacher","Playground","Park","Zoo","Rain","Umbrella","Wellington Boots"],
    tweens: ["Harry Potter","Hogwarts","Doctor Who","Sherlock Holmes","James Bond","Ed Sheeran","Harry Styles","Dua Lipa","Little Mix","One Direction","Adele","TikTok","YouTube","Instagram","Snapchat","Minecraft","Fortnite","Roblox","FIFA","Premier League","Manchester United","Liverpool","Arsenal","Chelsea","Harry Kane","Marcus Rashford","Bukayo Saka","Wimbledon","FA Cup","Netflix","Disney Plus","Stranger Things","Wednesday","Bridgerton","Nando's","Greggs","McDonald's","Fish and Chips","Cadbury","Percy Pigs","Tesco","Primark","JD Sports","London","Big Ben","London Eye"],
    teens: ["TikTok","Instagram","Snapchat","BeReal","Discord","Harry Styles","Dua Lipa","Ed Sheeran","Stormzy","Dave","Central Cee","Raye","Glastonbury","Reading Festival","Wireless","Netflix","BBC iPlayer","Love Island","Strictly","The Traitors","Peaky Blinders","Jude Bellingham","Bukayo Saka","Phil Foden","Premier League","Champions League","A-Levels","GCSEs","Sixth Form","University","UCAS","Prom","Gap Year","Nando's","Five Guys","Greggs","Pret","Primark","JD Sports","Zara","ASOS","Uber","Deliveroo","London Underground","Student Discount","Mental Health"],
    adults: ["David Beckham","Harry Kane","Jude Bellingham","Gareth Southgate","Ed Sheeran","Adele","Harry Styles","Dua Lipa","The Beatles","Queen","Coldplay","James Bond","Daniel Craig","Benedict Cumberbatch","Kate Winslet","Emma Watson","Game of Thrones","The Crown","Peaky Blinders","Fleabag","Love Island","Strictly","Premier League","Champions League","Wimbledon","The Ashes","Glastonbury","London","Edinburgh","Manchester","Big Ben","Tower Bridge","Stonehenge","Full English Breakfast","Roast Dinner","Fish and Chips","Afternoon Tea","Pub","Mortgage","Council Tax","NHS","Train Strike","Work From Home","Tesco","Sainsbury's","M&S","John Lewis","Wedding","Hen Do","Eurostar"],
    over40: ["Queen Elizabeth","Princess Diana","Royal Wedding","Jubilee","The Beatles","Rolling Stones","Queen","Elton John","David Bowie","Oasis","Spice Girls","James Bond","Sean Connery","Hugh Grant","Colin Firth","Helen Mirren","Mr Bean","Fawlty Towers","Only Fools and Horses","Coronation Street","EastEnders","Live Aid","Band Aid","Cool Britannia","1966 World Cup","Bobby Moore","Margaret Thatcher","Tony Blair","Brexit","Princess Diana Funeral","Fish and Chips","Full English","Sunday Roast","Marmite","Pub","Tea and Biscuits","Caravan Holiday","Blackpool","Butlins","Mini Cooper","Routemaster Bus","Top Gear","Blue Peter","Woolworths","Ceefax"],
    allAges: ["Queen Elizabeth","King Charles","Royal Family","Buckingham Palace","Big Ben","Tower of London","London Eye","Tower Bridge","Stonehenge","Harry Potter","James Bond","Mr Bean","Paddington Bear","The Beatles","Queen","Ed Sheeran","Adele","David Beckham","Fish and Chips","Roast Dinner","Full English","Afternoon Tea","Crumpets","Marmite","Red Bus","Black Cab","Underground","Union Jack","Royal Guard","BBC","Premier League","Wimbledon","Cricket","Rugby","Tesco","Marks & Spencer","Harrods","Greggs","Rain","Umbrella","Cup of Tea","Pub","Shakespeare","Doctor Who"]
  }},
  australia: { name: "Australia", flag: "🇦🇺", ages: {
    kids: ["Bluey","Bingo","Bandit","Chilli","Wiggles","Hi-5","Play School","Kangaroo","Koala","Wombat","Platypus","Emu","Crocodile","Shark","Dolphin","Beach","Swimming","Sandcastle","Rock Pool","Surfing","Vegemite","Tim Tam","Fairy Bread","Meat Pie","Lamington","Sausage Sizzle","Zooper Dooper","Sydney Opera House","Sydney Harbour Bridge","Uluru","Zoo","Wildlife Park","Footy","Cricket","Swimming","Soccer","Christmas in Summer","Easter","Australia Day","BBQ","Backyard","Pool","Playground","G'day","Mate","No Worries"],
    tweens: ["Bluey","Steve Irwin","Chris Hemsworth","Margot Robbie","Minecraft","Fortnite","Roblox","FIFA","TikTok","YouTube","Instagram","AFL","NRL","Cricket","State of Origin","Australian Open","Melbourne Cup","Tim Tam","Vegemite","Fairy Bread","Bunnings Snag","Meat Pie","Macca's","KFC","Hungry Jack's","Red Rooster","Sydney Opera House","Bondi Beach","Great Barrier Reef","Uluru","Gold Coast","Dreamworld","Movie World","Sea World","Luna Park","Kmart","Big W","JB Hi-Fi","Woolworths","Coles","Beach Cricket","Swimming Pool","Camping","G'day","Mate","Arvo"],
    teens: ["TikTok","Instagram","Snapchat","BeReal","Discord","The Kid Laroi","Tones and I","Troye Sivan","5SOS","Kylie Minogue","Splendour in the Grass","Falls Festival","Laneway","Netflix","Stan","Binge","Disney Plus","AFL","NRL","State of Origin","Australian Open","Melbourne Cup","Dustin Martin","Pat Cummins","Steve Smith","Fortnite","FIFA","Call of Duty","Valorant","Year 12","ATAR","Schoolies","Gap Year","Uni","Learner's Permit","P Plates","First Car","Part-time Job","Macca's","Guzman y Gomez","Nando's","Boba Tea","Cotton On","Bondi Beach","Byron Bay","Road Trip"],
    adults: ["Chris Hemsworth","Margot Robbie","Nicole Kidman","Hugh Jackman","Russell Crowe","Kylie Minogue","Keith Urban","Tame Impala","Flume","Sia","Steve Irwin","Crocodile Hunter","Bindi Irwin","AFL","NRL","State of Origin","Melbourne Cup","Australian Open","Cricket","The Ashes","Sydney Opera House","Great Barrier Reef","Uluru","Bondi Beach","Melbourne","Sydney","Bunnings Sausage Sizzle","BBQ","Tim Tam","Vegemite","Meat Pie","Pavlova","Flat White","VB","XXXX","Cooper's","Qantas","Property Market","Super","HECS Debt","Beach House","Caravan","Camping Trip","Road Trip","Kmart","Bunnings","Dan Murphy's","Woolworths"],
    over40: ["Steve Irwin","Crocodile Dundee","Paul Hogan","Dame Edna","Kylie Minogue","INXS","Midnight Oil","AC/DC","Bee Gees","Crowded House","Cold Chisel","Russell Crowe","Nicole Kidman","Mel Gibson","Heath Ledger","Olivia Newton-John","Neighbours","Home and Away","Hey Hey It's Saturday","Burke's Backyard","Don Bradman","Shane Warne","Glenn McGrath","Ian Thorpe","Cathy Freeman","Sydney Olympics 2000","Bicentenary","Holden Commodore","Ford Falcon","Ute","Kingswood","Vegemite","Tim Tam","Milo","Arnott's","Aeroplane Jelly","VB","XXXX","Foster's","Triple J","ABC"],
    allAges: ["Sydney Opera House","Sydney Harbour Bridge","Uluru","Great Barrier Reef","Kangaroo","Koala","Platypus","Wombat","Emu","Crocodile","Shark","Kookaburra","Steve Irwin","Chris Hemsworth","Nicole Kidman","Hugh Jackman","Kylie Minogue","AC/DC","Vegemite","Tim Tam","Meat Pie","Pavlova","Lamington","Bunnings Snag","BBQ","G'day Mate","No Worries","Fair Dinkum","Aussie","Arvo","Barbie","AFL","NRL","Cricket","Australian Open","Melbourne Cup","Beach","Surfing","Outback","Bush","Bluey","Qantas","Woolworths","Bunnings","Kmart","Australia Day","ANZAC Day","Christmas in Summer","Thongs","Ute","Maccas"]
  }},
  germany: { name: "Germany", flag: "🇩🇪", ages: {
    kids: ["Die Sendung mit der Maus","Bibi Blocksberg","Benjamin Blümchen","Die Biene Maja","Sandmännchen","Bratwurst","Pommes","Schnitzel","Brezel","Haribo","Kinder Überraschung","Milka","Nutella","Weihnachtsmarkt","Nikolaus","Osterhase","Adventskalender","Schultüte","Kindergarten","Spielplatz","Schwimmbad","Neuschwanstein","Schloss","Zoo","Freizeitpark","Legoland","Europa-Park","Fußball","Schwimmen","Fahrradfahren","Rotkäppchen","Hänsel und Gretel","Schneewittchen","Tanzen","Singen","Malen","Spielen"],
    tweens: ["Minecraft","Fortnite","Roblox","FIFA","TikTok","YouTube","Instagram","Bundesliga","Bayern München","Borussia Dortmund","RB Leipzig","Jamal Musiala","Florian Wirtz","Joshua Kimmich","Manuel Neuer","Netflix","Disney Plus","Harry Potter","Die drei ???","Bratwurst","Currywurst","Döner Kebab","Pizza","Burger","McDonald's","Burger King","KFC","Haribo","Milka","Ritter Sport","Europa-Park","Phantasialand","Legoland","Movie Park","Berlin","München","Hamburg","Köln","Frankfurt","iPhone","PlayStation","Xbox","Schule","Gymnasium","Ferien"],
    teens: ["TikTok","Instagram","Snapchat","BeReal","Discord","Apache 207","Capital Bra","Shirin David","Nina Chuba","Kontra K","Sido","Rock am Ring","Wacken","Lollapalooza Berlin","Netflix","Disney Plus","Dark","How to Sell Drugs Online","Bundesliga","Bayern München","Borussia Dortmund","Champions League","Jamal Musiala","Florian Wirtz","Kai Havertz","Abi","Abitur","Studium","Ausbildung","Führerschein","Nebenjob","Döner","Currywurst","Burger","Sushi","H&M","Zara","Nike","Adidas","About You","Berlin","München","Hamburg","Köln","Clubs","Festival"],
    adults: ["Angela Merkel","Olaf Scholz","Bayern München","Borussia Dortmund","Bundesliga","Thomas Müller","Manuel Neuer","Joshua Kimmich","Toni Kroos","Michael Schumacher","Sebastian Vettel","Formel 1","Boris Becker","Steffi Graf","Rammstein","Kraftwerk","Nena","Modern Talking","Diane Kruger","Daniel Brühl","Christoph Waltz","Heidi Klum","Tatort","Babylon Berlin","Dark","Oktoberfest","Weihnachtsmarkt","Karneval","Bratwurst","Schnitzel","Currywurst","Bier","Weißbier","Riesling","Glühwein","Autobahn","Deutsche Bahn","ICE","Mercedes","BMW","Volkswagen","Porsche","Berlin","München","Frankfurt","Brandenburger Tor","Neuschwanstein"],
    over40: ["Helmut Kohl","Fall der Mauer","Wiedervereinigung","DDR","Franz Beckenbauer","Gerd Müller","Lothar Matthäus","WM 1990","WM 2014","Boris Becker","Steffi Graf","Michael Schumacher","Formel 1","Nena","Modern Talking","Scorpions","Kraftwerk","Die Toten Hosen","Udo Lindenberg","Herbert Grönemeyer","Peter Maffay","Derrick","Wetten, dass..?","Thomas Gottschalk","Volkswagen Käfer","Golf","Trabant","Mercedes-Benz","Deutsche Mark","Euro-Umstellung","Bratwurst","Schnitzel","Schwarzwälder Kirschtorte","Pils","Weißbier","Altbier","Kölsch"],
    allAges: ["Brandenburger Tor","Neuschwanstein","Kölner Dom","Berlin","München","Autobahn","Deutsche Bahn","Volkswagen","Mercedes-Benz","BMW","Porsche","Bratwurst","Schnitzel","Bretzel","Schwarzwälder Kirschtorte","Bier","Oktoberfest","Weißbier","Riesling","Bundesliga","Bayern München","Borussia Dortmund","Weihnachtsmarkt","Glühwein","Adventskalender","Nikolaus","Angela Merkel","Michael Schumacher","Boris Becker","Steffi Graf","Beethoven","Bach","Goethe","Haribo","Milka","Ritter Sport","Kinder Überraschung","Adidas","Puma","Birkenstock","Lederhosen","Dirndl"]
  }},
  france: { name: "France", flag: "🇫🇷", ages: {
    kids: ["Astérix","Obélix","Tintin","Petit Nicolas","Babar","Les Schtroumpfs","Croissant","Pain au chocolat","Crêpes","Baguette","Chocolat chaud","Nutella","Tour Eiffel","Disneyland Paris","Château","Plage","Zoo","Parc","Football","Tennis","Natation","Vélo","Noël","Pâques","Anniversaire","Vacances","Roi","Reine","Prince","Princesse","Chevalier","Arc-en-ciel","Soleil","Lune","Étoile","Danser","Chanter","Dessiner","Jouer"],
    tweens: ["Kylian Mbappé","PSG","Olympique de Marseille","Ligue 1","Champions League","Minecraft","Fortnite","Roblox","FIFA","TikTok","YouTube","Instagram","Netflix","Disney Plus","Astérix","Tintin","Harry Potter","Disneyland Paris","Parc Astérix","Futuroscope","Croissant","Crêpes","Pain au chocolat","Baguette","Quiche","McDonald's","Quick","KFC","Haribo","Nutella","Tour Eiffel","Mont Saint-Michel","Château de Versailles","Paris","Nice","Marseille","Lyon","iPhone","PlayStation","Xbox","Collège","Vacances scolaires"],
    teens: ["TikTok","Instagram","Snapchat","BeReal","Discord","Aya Nakamura","Angèle","Orelsan","Ninho","Jul","Booba","PNL","Daft Punk","David Guetta","DJ Snake","Netflix","Disney Plus","Lupin","Emily in Paris","Kylian Mbappé","PSG","Champions League","Ligue 1","Équipe de France","Bac","Lycée","Parcoursup","Fac","Permis","Job d'été","Zara","H&M","Nike","Adidas","Vinted","McDonald's","Burger King","Starbucks","Paris","Nice","Bordeaux","Festival","Concert"],
    adults: ["Emmanuel Macron","Kylian Mbappé","Zinedine Zidane","PSG","Équipe de France","Teddy Riner","Tony Parker","Daft Punk","David Guetta","Phoenix","Marion Cotillard","Jean Dujardin","Omar Sy","Amélie","Intouchables","Croissant","Baguette","Fromage","Vin","Champagne","Crème brûlée","Tour Eiffel","Louvre","Versailles","Mont Saint-Michel","Paris","Nice","Cannes","Bordeaux","Lyon","Côte d'Azur","Provence","Louis Vuitton","Chanel","Dior","Hermès","Airbus","Renault","Peugeot","Air France","RTT","Grève","Vacances","Tour de France","Roland-Garros","Cannes Film Festival"],
    over40: ["Jacques Chirac","François Mitterrand","Charles de Gaulle","Michel Platini","Zinedine Zidane","Coupe du Monde 1998","Johnny Hallyday","Serge Gainsbourg","Édith Piaf","Charles Aznavour","Claude François","Gérard Depardieu","Jean-Paul Belmondo","Alain Delon","Brigitte Bardot","Les Bronzés","Le Dîner de Cons","La Grande Vadrouille","Les Visiteurs","Astérix","Tintin","Minitel","France 2","TF1","Croissant","Baguette","Camembert","Bordeaux","Champagne","2CV","Renault 4L","Peugeot 205","Tour de France","Roland-Garros"],
    allAges: ["Tour Eiffel","Louvre","Arc de Triomphe","Notre-Dame","Versailles","Mont Saint-Michel","Croissant","Baguette","Crêpes","Fromage","Vin","Champagne","Macarons","Kylian Mbappé","Zinedine Zidane","Équipe de France","PSG","Tour de France","Roland-Garros","Cannes","Napoléon","Marie-Antoinette","Louis XIV","Jeanne d'Arc","Daft Punk","Édith Piaf","David Guetta","Astérix","Tintin","Le Petit Prince","Les Schtroumpfs","Louis Vuitton","Chanel","Dior","Renault","Peugeot","Air France","Bonjour","Merci","Paris","Nice","Lyon","Marseille"]
  }},
  japan: { name: "Japan", flag: "🇯🇵", ages: {
    kids: ["Pikachu","Pokemon","Charizard","Eevee","Mario","Luigi","Princess Peach","Yoshi","Doraemon","Hello Kitty","Anpanman","Totoro","Ponyo","Sushi","Ramen","Onigiri","Bento Box","Pocky","Mochi","Mount Fuji","Cherry Blossom","Tokyo","Disneyland","Bullet Train","Origami","Kimono","Temple","Shrine","Swimming","Soccer","Baseball","Running","Dancing","School","Teacher","Birthday","Festival","Fireworks"],
    tweens: ["Pikachu","Pokemon","Mario","Zelda","Kirby","Splatoon","Nintendo Switch","Naruto","Dragon Ball","One Piece","Demon Slayer","My Hero Academia","Studio Ghibli","Spirited Away","Totoro","Minecraft","Fortnite","Roblox","Animal Crossing","TikTok","YouTube","LINE","Twitter","Sushi","Ramen","Udon","Tempura","Takoyaki","Pocky","Ramune","Tokyo","Osaka","Kyoto","Akihabara","Harajuku","Tokyo Disneyland","Universal Studios Japan","Baseball","Soccer","Shohei Ohtani"],
    teens: ["TikTok","YouTube","LINE","Twitter","Instagram","BTS","Blackpink","K-Pop","J-Pop","Anime","Demon Slayer","Jujutsu Kaisen","Attack on Titan","One Piece","My Hero Academia","Nintendo Switch","PlayStation","Pokemon","Genshin Impact","Shohei Ohtani","Naomi Osaka","Baseball","Soccer","J-League","Tokyo","Osaka","Shibuya","Harajuku","Akihabara","Uniqlo","GU","Don Quijote","Ramen","Sushi","Boba Tea","Convenience Store","High School","University Entrance Exam","Part-time Job","Train","Commute","Anime Convention","Cosplay"],
    adults: ["Shohei Ohtani","Naomi Osaka","Yuzuru Hanyu","Baseball","Sumo","Hayao Miyazaki","Studio Ghibli","Takeshi Kitano","Akira Kurosawa","Nintendo","Sony","Toyota","Honda","Uniqlo","Sushi","Ramen","Wagyu Beef","Kaiseki","Izakaya","Sake","Sapporo","Asahi","Japanese Whisky","Matcha","Tokyo","Kyoto","Osaka","Hiroshima","Nara","Mount Fuji","Cherry Blossom","Onsen","Ryokan","Shinkansen","Tokyo Metro","Emperor","Golden Week","Anime","Manga","Cosplay","Akihabara","Shibuya Crossing","Tokyo Tower"],
    over40: ["Akira Kurosawa","Seven Samurai","Godzilla","Sony Walkman","Nintendo","Sega","Game Boy","Pac-Man","Super Mario","Sonic","Street Fighter","Final Fantasy","Hayao Miyazaki","Studio Ghibli","Spirited Away","Totoro","Sadaharu Oh","Ichiro Suzuki","Sumo Wrestling","Tokyo Olympics 1964","Bubble Economy","Emperor Hirohito","Bullet Train","Toyota Corolla","Honda Civic","Sushi","Tempura","Sukiyaki","Sake","Sapporo","Karaoke","Pachinko","Samurai","Ninja","Geisha","Kimono","Origami","Tea Ceremony","Mount Fuji","Kyoto"],
    allAges: ["Mount Fuji","Tokyo","Kyoto","Cherry Blossom","Shinkansen","Sushi","Ramen","Tempura","Matcha","Mochi","Pokemon","Pikachu","Mario","Nintendo","Sony","Hello Kitty","Totoro","Studio Ghibli","Anime","Manga","Samurai","Ninja","Geisha","Sumo","Karate","Kimono","Origami","Bonsai","Tea Ceremony","Emperor","Shrine","Temple","Torii Gate","Toyota","Honda","Bullet Train","Robot","Shohei Ohtani","Baseball","Cherry Blossom Festival","Tokyo Tower","Shibuya Crossing","Akihabara","Harajuku","Kawaii","Cosplay"]
  }},
  brazil: { name: "Brazil", flag: "🇧🇷", ages: {
    kids: ["Turma da Mônica","Mônica","Cebolinha","Cascão","Magali","Galinha Pintadinha","Pelé","Neymar","Futebol","Seleção","Copa do Mundo","Praia","Piscina","Parque","Zoológico","Pizza","Brigadeiro","Bolo","Sorvete","Pipoca","Guaraná","Carnaval","Natal","Páscoa","Aniversário","Festa Junina","Arara","Tucano","Macaco","Jacaré","Onça","Cristo Redentor","Praia de Copacabana","Amazônia","Escola","Professor","Férias","Dançar","Cantar","Desenhar","Brincar","Nadar"],
    tweens: ["Neymar","Vinícius Jr","Endrick","Seleção Brasileira","Copa do Mundo","Flamengo","Corinthians","Palmeiras","São Paulo","Santos","Minecraft","Fortnite","Roblox","Free Fire","FIFA","TikTok","YouTube","Instagram","WhatsApp","Felipe Neto","Luccas Neto","Netflix","Disney Plus","Praia","Piscina","Shopping","Parque de diversões","Beto Carrero","Beach Park","Pizza","Hambúrguer","Açaí","Coxinha","Brigadeiro","McDonald's","Burger King","Bob's","iPhone","PlayStation","Xbox","Rio de Janeiro","São Paulo","Praia"],
    teens: ["TikTok","Instagram","WhatsApp","Twitter","YouTube","Anitta","Luísa Sonza","Gusttavo Lima","Marília Mendonça","Jorge & Mateus","Funk","Sertanejo","Trap","Piseiro","Pagode","Neymar","Vinícius Jr","Flamengo","Corinthians","Palmeiras","Netflix","Globoplay","Disney Plus","BBB","A Fazenda","Fortnite","Free Fire","Valorant","FIFA","ENEM","Vestibular","Faculdade","Carteira de motorista","Açaí","Hambúrguer","Coxinha","Pizza","Sushi","iFood","Uber","99","Shopping","Praia","Balada","Rock in Rio","Lollapalooza","Carnaval"],
    adults: ["Neymar","Vinícius Jr","Pelé","Ronaldo","Ronaldinho","Copa do Mundo","Seleção Brasileira","Flamengo","Corinthians","Palmeiras","Ayrton Senna","Fórmula 1","Anitta","Ivete Sangalo","Gilberto Gil","Caetano Veloso","Tom Jobim","Gisele Bündchen","Rodrigo Santoro","Wagner Moura","Cidade de Deus","Tropa de Elite","Central do Brasil","Feijoada","Churrasco","Picanha","Caipirinha","Açaí","Guaraná","Brahma","Skol","Cristo Redentor","Copacabana","Ipanema","Amazônia","Rio de Janeiro","São Paulo","Salvador","Brasília","Carnaval","Réveillon","Festa Junina","Rock in Rio","Petrobras","Nubank","Mercado Livre"],
    over40: ["Pelé","Garrincha","Zico","Romário","Ronaldo","Copa de 70","Copa de 94","Copa de 2002","Ayrton Senna","Nelson Piquet","Emerson Fittipaldi","Tom Jobim","Vinícius de Moraes","Elis Regina","Chico Buarque","Roberto Carlos","Xuxa","Angélica","Sílvio Santos","Chacrinha","Hebe Camargo","Novela das 8","TV Globo","Feijoada","Churrasco","Caipirinha","Guaraná","Chopp","Fusca","Brasília","Kombi","Gol","Hiperinflação","Plano Real","Copacabana","Ipanema","Cristo Redentor","Maracanã","Carnaval","Escola de Samba","Sambódromo"],
    allAges: ["Cristo Redentor","Copacabana","Ipanema","Amazônia","Rio de Janeiro","São Paulo","Salvador","Maracanã","Pelé","Neymar","Ronaldo","Ronaldinho","Seleção Brasileira","Futebol","Copa do Mundo","Flamengo","Corinthians","Carnaval","Samba","Bossa Nova","Festa Junina","Feijoada","Churrasco","Açaí","Brigadeiro","Pão de Queijo","Caipirinha","Guaraná","Picanha","Arara","Tucano","Onça","Macaco","Jacaré","Anitta","Ivete Sangalo","Tom Jobim","Ayrton Senna","Fórmula 1","Gisele Bündchen","Praia","Sol","Tropical","Havaianas","Turma da Mônica"]
  }},
  india: { name: "India", flag: "🇮🇳", ages: {
    kids: ["Chhota Bheem","Motu Patlu","Doraemon","Shinchan","Pokemon","Ninja Hattori","Taj Mahal","Red Fort","Zoo","Park","Beach","Cricket","Kabaddi","Swimming","Running","Samosa","Pakora","Pani Puri","Kulfi","Gulab Jamun","Chai","Lassi","Mango","Banana","Diwali","Holi","Rakhi","Ganesh Chaturthi","Birthday","School","Teacher","Homework","Summer Vacation","Elephant","Tiger","Lion","Monkey","Peacock","Cow","Train","Auto Rickshaw","Bus","Dancing","Singing","Drawing","Playing","Namaste","Bollywood"],
    tweens: ["Virat Kohli","MS Dhoni","Sachin Tendulkar","Rohit Sharma","IPL","World Cup","Cricket","CSK","MI","RCB","Minecraft","Fortnite","PUBG Mobile","Free Fire","FIFA","TikTok","YouTube","Instagram","WhatsApp","CarryMinati","BB Ki Vines","Technical Guruji","Netflix","Amazon Prime","Disney Plus Hotstar","Stranger Things","Wednesday","KGF","Samosa","Biryani","Pizza","Burger","Momos","Maggi","McDonald's","Domino's","KFC","Pizza Hut","Taj Mahal","Goa","Kerala","Jaipur","Mumbai","Diwali","Holi","Durga Puja"],
    teens: ["TikTok","Instagram","YouTube","Snapchat","WhatsApp","Virat Kohli","MS Dhoni","Rohit Sharma","IPL","World Cup","Arijit Singh","Shreya Ghoshal","Badshah","Honey Singh","AP Dhillon","Shah Rukh Khan","Pathaan","Jawan","Animal","KGF","Alia Bhatt","Deepika Padukone","Ranbir Kapoor","Ranveer Singh","Netflix","Prime Video","Hotstar","Sacred Games","Mirzapur","JEE","NEET","Board Exams","Coaching","IIT","Driving License","First Bike","Part-time Job","Biryani","Momos","Butter Chicken","Pani Puri","Zomato","Swiggy","Uber","Ola","Myntra","Flipkart","Goa","Manali","Ladakh","Kerala"],
    adults: ["Virat Kohli","Sachin Tendulkar","MS Dhoni","IPL","World Cup","Cricket","Shah Rukh Khan","Salman Khan","Aamir Khan","Amitabh Bachchan","Priyanka Chopra","Deepika Padukone","Alia Bhatt","Pathaan","Jawan","RRR","Bahubali","KGF","AR Rahman","Arijit Singh","Kishore Kumar","Netflix","Prime Video","Hotstar","Mirzapur","Sacred Games","Narendra Modi","Parliament","Elections","Taj Mahal","Red Fort","Gateway of India","Mumbai","Delhi","Bangalore","Hyderabad","Chennai","Curry","Biryani","Butter Chicken","Dosa","Samosa","Chai","Lassi","Kingfisher","Old Monk","Tata","Reliance","Infosys","Wipro","Diwali","Holi","Durga Puja","Eid"],
    over40: ["Sachin Tendulkar","Kapil Dev","Sunil Gavaskar","1983 World Cup","2011 World Cup","Amitabh Bachchan","Shah Rukh Khan","Rajesh Khanna","Dilip Kumar","Hema Malini","Rekha","Madhuri Dixit","Sridevi","Sholay","DDLJ","Mughal-e-Azam","Mother India","Lata Mangeshkar","Mohammed Rafi","Kishore Kumar","RD Burman","Doordarshan","Ramayana","Mahabharat","Hum Log","Indira Gandhi","Rajiv Gandhi","Atal Bihari Vajpayee","Ambassador Car","Maruti 800","Bajaj Scooter","Taj Mahal","Red Fort","Jaipur","Varanasi","Curry","Biryani","Roti","Dal","Chai","Thums Up","All India Radio","Chitrahaar"],
    allAges: ["Taj Mahal","Red Fort","Gateway of India","Jaipur","Mumbai","Delhi","Bangalore","Chennai","Kolkata","Virat Kohli","Sachin Tendulkar","MS Dhoni","Cricket","IPL","World Cup","Shah Rukh Khan","Amitabh Bachchan","Bollywood","Curry","Biryani","Butter Chicken","Dosa","Samosa","Naan","Chai","Lassi","Gulab Jamun","Diwali","Holi","Ganesh Chaturthi","Eid","Elephant","Tiger","Peacock","Cow","Namaste","Yoga","Meditation","Sari","Bindi","AR Rahman","Lata Mangeshkar","Rickshaw","Train","Tata","Reliance","Gandhi","Mother Teresa"]
  }},
  italy: { name: "Italy", flag: "🇮🇹", ages: {
    kids: ["Pizza","Pasta","Spaghetti","Gelato","Lasagna","Pinocchio","Geronimo Stilton","Winx Club","Ferrari","Vespa","Gondola","Train","Colosseum","Leaning Tower of Pisa","Venice","Rome","Beach","Mountains","Zoo","Park","Playground","Football","Swimming","Cycling","Christmas","Easter","Carnival","Birthday","Mamma","Papà","Nonna","Nonno","Family","Dancing","Singing","Drawing","Playing"],
    tweens: ["Minecraft","Fortnite","Roblox","FIFA","TikTok","YouTube","Instagram","Me contro Te","Favij","Netflix","Disney Plus","Harry Potter","Juventus","Milan","Inter","Roma","Napoli","Serie A","Champions League","Pizza","Pasta","Gelato","Panini","Nutella","McDonald's","Burger King","Kinder","Ferrero Rocher","Mulino Bianco","Rome","Milan","Venice","Florence","Naples","Colosseum","Leaning Tower","Vatican","Gondola","Gardaland","Mirabilandia","iPhone","PlayStation","Xbox"],
    teens: ["TikTok","Instagram","YouTube","WhatsApp","BeReal","Måneskin","Blanco","Mahmood","Elodie","Sfera Ebbasta","Sanremo","X Factor Italia","Festival","Concert","Netflix","Disney Plus","Mare Fuori","Skam Italia","Juventus","Milan","Inter","Napoli","Champions League","Ferrari","Formula 1","MotoGP","Serie A","Maturità","Università","Erasmus","Patente","Lavoretto estivo","Pizza","Pasta","Aperitivo","Spritz","Gelato","Zara","H&M","Nike","Adidas","Gucci","Rome","Milan","Florence","Naples","Bologna"],
    adults: ["Ferrari","Lamborghini","Fiat","Alfa Romeo","Maserati","Juventus","Milan","Inter","Napoli","Serie A","Champions League","Francesco Totti","Alessandro Del Piero","Paolo Maldini","Gianluigi Buffon","Valentino Rossi","MotoGP","Formula 1","Charles Leclerc","Giorgio Armani","Gucci","Prada","Versace","Dolce & Gabbana","Sophia Loren","Monica Bellucci","Roberto Benigni","La Dolce Vita","Cinema Paradiso","La Vita è Bella","Pizza","Pasta","Risotto","Tiramisù","Gelato","Espresso","Cappuccino","Prosecco","Chianti","Barolo","Rome","Milan","Florence","Venice","Naples","Colosseum","Vatican","Leaning Tower","Amalfi Coast","Tuscany","Lake Como","La Scala","Opera","Renaissance","Fashion"],
    over40: ["Ferrari","Lamborghini","Fiat 500","Vespa","Roberto Baggio","Paolo Rossi","Paolo Maldini","World Cup 1982","World Cup 2006","Eros Ramazzotti","Zucchero","Andrea Bocelli","Laura Pausini","Luciano Pavarotti","Sophia Loren","Marcello Mastroianni","Alberto Sordi","Federico Fellini","La Dolce Vita","Neorealismo","RAI","Fantastico","Domenica In","Carosello","Pizza","Pasta","Ragù","Carbonara","Tiramisù","Espresso","Cappuccino","Grappa","Limoncello","Rome","Milan","Florence","Venice","Colosseum","Vatican","Sistine Chapel","Renaissance","Michelangelo","Leonardo da Vinci"],
    allAges: ["Colosseum","Leaning Tower of Pisa","Vatican","Venice","Rome","Milan","Florence","Naples","Sicily","Pizza","Pasta","Gelato","Lasagna","Tiramisù","Espresso","Cappuccino","Prosecco","Mozzarella","Ferrari","Lamborghini","Vespa","Fiat","Juventus","Milan","Inter","Serie A","Calcio","Leonardo da Vinci","Michelangelo","Renaissance","Gucci","Prada","Armani","Versace","Andrea Bocelli","Pavarotti","Opera","La Scala","Pinocchio","Sophia Loren","Roberto Benigni","Gondola","Amalfi Coast","Tuscany","Lake Como","Ciao","Mamma Mia","Bella"]
  }},
  spain: { name: "Spain", flag: "🇪🇸", ages: {
    kids: ["Pocoyó","Peppa Pig","Paw Patrol","Pokemon","Real Madrid","Barcelona","Football","La Liga","Paella","Churros","Tortilla","Helado","Beach","Pool","Playground","Zoo","Park","Swimming","Football","Dancing","Christmas","Three Kings Day","Easter","Birthday","Carnival","School","Teacher","Homework","Summer Vacation","Mamá","Papá","Abuela","Abuelo","Sun","Beach","Sand","Sea","Castle","Barcelona","Madrid"],
    tweens: ["Minecraft","Fortnite","Roblox","FIFA","TikTok","YouTube","Instagram","El Rubius","Ibai","TheGrefg","AuronPlay","Vegetta777","Netflix","Disney Plus","La Casa de Papel","Élite","Stranger Things","Real Madrid","Barcelona","Atlético","La Liga","Vinícius Jr","Pedri","Gavi","Bellingham","Champions League","Paella","Tortilla","Churros","Pizza","Hamburguesa","McDonald's","Burger King","Telepizza","ColaCao","Phoskitos","Bollycao","Nocilla","Barcelona","Madrid","Valencia","Sevilla","Port Aventura","Warner Madrid","iPhone","PlayStation","Xbox"],
    teens: ["TikTok","Instagram","YouTube","WhatsApp","BeReal","Rosalía","Bad Bunny","C. Tangana","Quevedo","Aitana","Bizarrap","Primavera Sound","Mad Cool","Arenal Sound","Netflix","HBO Max","Disney Plus","La Casa de Papel","Élite","Real Madrid","Barcelona","Atlético","La Liga","Champions League","Vinícius Jr","Pedri","Gavi","Bellingham","Rodri","Carlos Alcaraz","Rafael Nadal","Tennis","Wimbledon","Selectividad","Universidad","Bachillerato","Carnet de conducir","Trabajo de verano","Tapas","Paella","Tortilla","Sangría","Cerveza","Zara","Mango","Pull & Bear","Bershka","Ibiza","Barcelona","Madrid","Valencia","Botellón","Festival"],
    adults: ["Real Madrid","Barcelona","Atlético","La Liga","Champions League","Rafael Nadal","Carlos Alcaraz","Tennis","Grand Slam","Fernando Alonso","Formula 1","Marc Márquez","MotoGP","Rosalía","Enrique Iglesias","Julio Iglesias","Alejandro Sanz","Penélope Cruz","Javier Bardem","Antonio Banderas","Pedro Almodóvar","La Casa de Papel","Élite","Gran Hotel","Paella","Tapas","Jamón Ibérico","Gazpacho","Tortilla","Rioja","Cava","Sangría","Cerveza","Barcelona","Madrid","Sevilla","Valencia","Bilbao","Sagrada Familia","Alhambra","La Rambla","Prado","Bernabéu","Ibiza","Mallorca","Costa del Sol","Canarias","Zara","Inditex","Seat","Iberia","Siesta","Fiesta","Flamenco","Tomatina","San Fermín"],
    over40: ["Rafael Nadal","Iker Casillas","Xavi","Iniesta","Fernando Torres","World Cup 2010","Euro 2008","Euro 2012","La Roja","Miguel Induráin","Tour de France","Fernando Alonso","Formula 1","Julio Iglesias","Raphael","Rocío Jurado","Mecano","Héroes del Silencio","Penélope Cruz","Antonio Banderas","Javier Bardem","Pedro Almodóvar","TVE","Un, dos, tres","Verano Azul","Paella","Tortilla","Jamón","Tapas","Gazpacho","Rioja","Jerez","Cava","Sangría","Seat 600","Seat Ibiza","Transición","Juan Carlos I","Barcelona 92","Expo 92"],
    allAges: ["Sagrada Familia","Alhambra","La Rambla","Prado","Bernabéu","Barcelona","Madrid","Sevilla","Valencia","Granada","Paella","Tapas","Tortilla","Jamón","Churros","Gazpacho","Sangría","Real Madrid","Barcelona","La Liga","El Clásico","Rafael Nadal","Carlos Alcaraz","Tennis","Flamenco","Tomatina","San Fermín","Feria de Abril","Ibiza","Mallorca","Costa del Sol","Canarias","Penélope Cruz","Antonio Banderas","Pedro Almodóvar","Picasso","Dalí","Gaudí","Miró","Zara","Seat","Iberia","Siesta","Fiesta","Olé","Hola"]
  }},
  mexico: { name: "Mexico", flag: "🇲🇽", ages: {
    kids: ["El Chavo del 8","El Chapulín Colorado","Dora la Exploradora","Coco","Ferdinand","Piñata","Mariachi","Sombrero","Maracas","Tacos","Quesadilla","Churros","Helado","Paletas","Chocolate abuelita","Mazapán","Día de Muertos","Navidad","Posadas","Reyes Magos","Perro","Gato","Perico","Tortuga","Football","Swimming","Dancing","Playing","Beach","Pool","Park","Zoo","Playground","School","Teacher","Vacation","Mamá","Papá","Abuela","Abuelo","Aztec Pyramid"],
    tweens: ["Minecraft","Fortnite","Roblox","Free Fire","FIFA","TikTok","YouTube","Instagram","Luisito Comunica","Juanpa Zurita","Kimberly Loaiza","Netflix","Disney Plus","Prime Video","Club América","Chivas","Cruz Azul","Pumas","Tigres","Liga MX","Selección Mexicana","Tacos","Quesadillas","Tortas","Pizzas","Hamburguesas","McDonald's","Burger King","Domino's","Sabritas","Gansito","Pingüinos","Mazapán","Chichén Itzá","Cancún","Los Cabos","CDMX","Acapulco","Six Flags","Xcaret","Día de Muertos","Independence Day"],
    teens: ["TikTok","Instagram","YouTube","WhatsApp","Twitter","Bad Bunny","Peso Pluma","Natanael Cano","Grupo Firme","Fuerza Regida","Danna Paola","Karol G","Belinda","Corridos Tumbados","Reggaeton","Regional Mexicano","Netflix","Disney Plus","HBO Max","Luis Miguel La Serie","Club América","Chivas","Cruz Azul","Liga MX","Checo Pérez","Formula 1","Red Bull Racing","Canelo Álvarez","Boxing","UFC","Prepa","Universidad","UNAM","Tec","Licencia de conducir","Primer trabajo","Tacos","Tortas","Pozole","Tamales","Michelada","Zara","H&M","Liverpool","CDMX","Guadalajara","Monterrey","Cancún","Playa del Carmen"],
    adults: ["Checo Pérez","Canelo Álvarez","Chicharito","Hugo Sánchez","Formula 1","Red Bull Racing","Boxing","Liga MX","Club América","Chivas","Cruz Azul","Pumas","Tigres","Luis Miguel","Juan Gabriel","Vicente Fernández","José José","Peso Pluma","Bad Bunny","Grupo Firme","Banda MS","Salma Hayek","Gael García Bernal","Diego Luna","Eugenio Derbez","Alfonso Cuarón","Guillermo del Toro","Alejandro Iñárritu","Tacos","Pozole","Mole","Tamales","Birria","Tequila","Mezcal","Margarita","Michelada","Corona","Chichén Itzá","Teotihuacán","Cancún","CDMX","Oaxaca","Día de Muertos","Cinco de Mayo","Independence Day","Mariachi","Lucha Libre","Frida Kahlo","Diego Rivera"],
    over40: ["Hugo Sánchez","Rafael Márquez","Cuauhtémoc Blanco","Jorge Campos","World Cup 1986","Azteca Stadium","El Tri","Julio César Chávez","Boxing","Luis Miguel","Juan Gabriel","Vicente Fernández","José José","Rocío Dúrcal","Gloria Trevi","Thalía","Timbiriche","El Chavo del 8","El Chapulín Colorado","Chespirito","Pedro Infante","Jorge Negrete","Cantinflas","María Félix","Televisa","TV Azteca","Siempre en Domingo","Carlos Slim","Telmex","PRI","PAN","Tacos","Pozole","Mole","Chiles en Nogada","Tamales","Tequila","Mezcal","Corona","VW Beetle","Vocho","Chichén Itzá","Teotihuacán","Acapulco","Frida Kahlo","Diego Rivera"],
    allAges: ["Chichén Itzá","Teotihuacán","Cancún","CDMX","Acapulco","Tacos","Quesadilla","Guacamole","Enchiladas","Pozole","Tequila","Margarita","Corona","Mezcal","Mariachi","Sombrero","Piñata","Lucha Libre","Día de Muertos","Cinco de Mayo","Independence Day","Frida Kahlo","Diego Rivera","Aztec","Maya","Club América","Chivas","Liga MX","El Tri","Luis Miguel","Juan Gabriel","Vicente Fernández","Canelo Álvarez","Checo Pérez","Hugo Sánchez","El Chavo del 8","Chespirito","Cantinflas","Salma Hayek","Gael García Bernal","Guillermo del Toro","Mexican Flag","Eagle","Cactus"]
  }},
  canada: { name: "Canada", flag: "🇨🇦", ages: {
    kids: ["Paw Patrol","Bluey","Peppa Pig","Cocomelon","Blippi","Hockey","Skating","Skiing","Swimming","Soccer","Maple Syrup","Pancakes","Poutine","Timbits","Hot Chocolate","Tim Hortons","CN Tower","Niagara Falls","Banff","Mountains","Beach","Zoo","Playground","Moose","Beaver","Bear","Goose","Polar Bear","Christmas","Halloween","Canada Day","Thanksgiving","Easter","Winter","Snow","Snowman","Toboggan","Ice Skating","School","Teacher","Recess","Summer Vacation","Hockey Stick","Skates","Mittens","Toque"],
    tweens: ["Minecraft","Fortnite","Roblox","NHL","FIFA","TikTok","YouTube","Instagram","MrBeast","Dream","PewDiePie","Netflix","Disney Plus","Crave","Stranger Things","Wednesday","Toronto Maple Leafs","Montreal Canadiens","Edmonton Oilers","Connor McDavid","Auston Matthews","Sidney Crosby","NHL","Hockey","Stanley Cup","Toronto Raptors","Blue Jays","Poutine","Tim Hortons","Timbits","Iced Capp","BeaverTails","McDonald's","A&W","Harvey's","CN Tower","Niagara Falls","Banff","Whistler","Canada's Wonderland","iPhone","PlayStation","Xbox"],
    teens: ["TikTok","Instagram","Snapchat","BeReal","Discord","Drake","The Weeknd","Justin Bieber","Shawn Mendes","Alessia Cara","Carly Rae Jepsen","Avril Lavigne","Netflix","Crave","Disney Plus","Schitt's Creek","Degrassi","Kim's Convenience","Connor McDavid","Auston Matthews","Sidney Crosby","NHL","Toronto Maple Leafs","Montreal Canadiens","Toronto Raptors","Bianca Andreescu","Denis Shapovalov","University","College","OSAP","G1","G2","Driver's License","Poutine","Tim Hortons","Boba Tea","Shawarma","Roots","Aritzia","Lululemon","Canada Goose","Toronto","Vancouver","Montreal","Banff","Cottage","Camping","Skiing"],
    adults: ["Drake","The Weeknd","Justin Bieber","Celine Dion","Shawn Mendes","Ryan Gosling","Ryan Reynolds","Rachel McAdams","Keanu Reeves","Jim Carrey","Mike Myers","Seth Rogen","Michael J. Fox","Justin Trudeau","Parliament","Ottawa","Connor McDavid","Sidney Crosby","Wayne Gretzky","NHL","Toronto Maple Leafs","Montreal Canadiens","Stanley Cup","Toronto Raptors","Blue Jays","CFL","Poutine","Maple Syrup","Tim Hortons","BeaverTails","Nanaimo Bars","CN Tower","Niagara Falls","Banff","Rocky Mountains","Toronto","Vancouver","Montreal","Calgary","Ottawa","Cottage Country","Muskoka","Whistler","Jasper","Tim Hortons","Lululemon","Roots","Canada Goose","RRSP","TFSA","Healthcare"],
    over40: ["Wayne Gretzky","Mario Lemieux","Bobby Orr","Gordie Howe","Sidney Crosby","1972 Summit Series","Canada Cup","Celine Dion","Bryan Adams","Alanis Morissette","Shania Twain","Neil Young","Joni Mitchell","Leonard Cohen","Rush","Jim Carrey","Mike Myers","John Candy","Rick Moranis","Michael J. Fox","Keanu Reeves","Dan Aykroyd","William Shatner","SCTV","Kids in the Hall","Corner Gas","Trailer Park Boys","CBC","Hockey Night in Canada","Don Cherry","Pierre Trudeau","Jean Chrétien","Brian Mulroney","Expo 67","1988 Calgary Olympics","Toronto Blue Jays World Series","Poutine","Maple Syrup","Tim Hortons","Canadian Tire","Loonie","Toonie","GST","Molson Canadian","Labatt Blue"],
    allAges: ["CN Tower","Niagara Falls","Banff","Rocky Mountains","Toronto","Vancouver","Montreal","Calgary","Ottawa","Wayne Gretzky","Sidney Crosby","Connor McDavid","NHL","Toronto Maple Leafs","Montreal Canadiens","Stanley Cup","Maple Leaf","Beaver","Moose","Polar Bear","Canadian Goose","Poutine","Maple Syrup","Tim Hortons","BeaverTails","Drake","Celine Dion","Justin Bieber","The Weeknd","Ryan Gosling","Ryan Reynolds","Jim Carrey","Keanu Reeves","Hockey","Curling","Skiing","Snowboarding","Lacrosse","Canada Day","Thanksgiving","RCMP","Mounties","Sorry","Eh","Loonie","Toonie","Toque","Roots","Canada Goose","Lululemon","Northern Lights"]
  }},
  ireland: { name: "Ireland", flag: "🇮🇪", ages: {
    kids: ["Leprechaun","Shamrock","Rainbow","Pot of Gold","Fairy","Peppa Pig","Bluey","Paw Patrol","GAA","Hurling","Football","Soccer","Swimming","Fish and Chips","Sausages","Tayto","Barry's Tea","Chocolate","Dublin Zoo","Playground","Park","Beach","Farm","Sheep","Cow","Horse","St. Patrick's Day","Christmas","Easter","Halloween","School","Teacher","Summer Holidays","Mammy","Daddy","Granny","Grandad","Rain","Rainbow","Wellies","Umbrella","Dancing","Singing","Drawing","Playing"],
    tweens: ["Minecraft","Fortnite","Roblox","FIFA","TikTok","YouTube","Instagram","Jacksepticeye","CallMeKevin","RTÉ","Netflix","GAA","All-Ireland","Dublin","Kerry","Mayo","Hurling","Football","Rugby","Tayto","Brennans Bread","Barry's Tea","Cadbury","Supermac's","McDonald's","KFC","Apache Pizza","Penneys","Sports Direct","JD Sports","Smyths","Dublin","Cork","Galway","Limerick","Trinity College","Cliffs of Moher","Giant's Causeway","Christmas Market","Halloween","Paddy's Day","iPhone","PlayStation","Xbox"],
    teens: ["TikTok","Instagram","Snapchat","BeReal","Discord","Hozier","Niall Horan","Dermot Kennedy","Picture This","The Script","Kodaline","Fontaines D.C.","CMAT","Electric Picnic","Longitude","Concert","Festival","Netflix","Disney Plus","Prime Video","Normal People","Derry Girls","GAA","All-Ireland Final","Croke Park","Hurling","Football","Rugby","Leaving Cert","CAO","College","University","Driving Test","First Car","Part-time Job","Penneys","Zara","JD Sports","Brown Thomas","Supermac's","Eddie Rockets","Nando's","Five Guys","Temple Bar","Galway","Cork","Pints","Nightclub","Craic"],
    adults: ["Conor McGregor","UFC","Boxing","GAA","All-Ireland","Croke Park","Hurling","Football","Kilkenny","Limerick","Dublin","Kerry","Mayo","Ireland Rugby","Johnny Sexton","Six Nations","Rory McIlroy","Shane Lowry","Golf","Ryder Cup","Hozier","U2","The Cranberries","Sinéad O'Connor","Niall Horan","Dermot Kennedy","Westlife","Cillian Murphy","Saoirse Ronan","Colin Farrell","Liam Neeson","Normal People","Derry Girls","Father Ted","The Banshees","Guinness","Jameson","Baileys","Irish Coffee","Full Irish Breakfast","Soda Bread","Tayto","Barry's Tea","Temple Bar","Cliffs of Moher","Ring of Kerry","Wild Atlantic Way","Dublin","Cork","Galway","Killarney","Ryanair","Aer Lingus","Penneys","Supermac's"],
    over40: ["U2","Bono","The Edge","Beautiful Day","The Cranberries","Dolores O'Riordan","Sinéad O'Connor","Van Morrison","Thin Lizzy","The Pogues","Enya","Boyzone","Westlife","B*Witched","The Corrs","Roy Keane","Jack Charlton","Italia 90","USA 94","Brian O'Driscoll","Ronan O'Gara","Ireland Rugby","Grand Slam","DJ Carey","Brian Cody","Henry Shefflin","Kilkenny Hurling","Liam Neeson","Pierce Brosnan","Gabriel Byrne","Father Ted","Mrs Brown's Boys","Glenroe","Fair City","The Late Late Show","Gay Byrne","RTÉ","TG4","Celtic Tiger","Good Friday Agreement","Guinness","Smithwick's","Irish Pub","Full Irish","Bacon and Cabbage","Ford Escort","Hiace Van"],
    allAges: ["Leprechaun","Shamrock","Pot of Gold","Rainbow","Clover","Guinness","Jameson","Irish Coffee","Baileys","St. Patrick's Day","Paddy's Day","Parade","Green","Dublin","Cork","Galway","Limerick","Cliffs of Moher","Ring of Kerry","Giant's Causeway","Temple Bar","GAA","Hurling","Football","Croke Park","All-Ireland","Ireland Rugby","Six Nations","U2","The Cranberries","Hozier","Niall Horan","Conor McGregor","Rory McIlroy","Katie Taylor","Cillian Murphy","Saoirse Ronan","Colin Farrell","Liam Neeson","Fish and Chips","Full Irish","Tayto","Barry's Tea","Craic","Pub","Riverdance","Irish Flag","Harp","Celtic"]
  }},
  netherlands: { name: "Netherlands", flag: "🇳🇱", ages: {
    kids: ["Nijntje","Miffy","Dikkie Dik","Jip en Janneke","Peppa Pig","Paw Patrol","Bluey","Pokemon","Bicycle","Windmill","Tulip","Canal","Boat","Pancakes","Stroopwafel","Hagelslag","Frikandel","Kroket","Cheese","Beach","Playground","Zoo","Park","Farm","Cow","Sheep","Horse","Duck","Sinterklaas","Christmas","Easter","King's Day","Birthday","School","Teacher","Summer Vacation","Cycling","Swimming","Soccer","Skating"],
    tweens: ["Minecraft","Fortnite","Roblox","FIFA","TikTok","YouTube","Instagram","Enzo Knol","Dylan Haegens","Kalvijn","StukTV","Netflix","Disney Plus","Videoland","Ajax","PSV","Feyenoord","Eredivisie","Champions League","Virgil van Dijk","Frenkie de Jong","Memphis Depay","Frikandel","Kroket","Stroopwafel","Hagelslag","Pannenkoeken","McDonald's","Burger King","KFC","FEBO","Efteling","Walibi","Madurodam","Duinrell","Amsterdam","Rotterdam","Utrecht","The Hague","Sinterklaas","King's Day","Carnival"],
    teens: ["TikTok","Instagram","YouTube","Snapchat","BeReal","Martin Garrix","Tiësto","Armin van Buuren","Afrojack","Hardwell","Davina Michelle","Snelle","Lil Kleine","Ronnie Flex","Amsterdam Dance Event","Mysteryland","Lowlands","Pinkpop","Netflix","Videoland","Disney Plus","Ajax","PSV","Feyenoord","Eredivisie","Champions League","Virgil van Dijk","Frenkie de Jong","Cody Gakpo","Xavi Simons","Max Verstappen","Formula 1","Red Bull Racing","Zandvoort","VWO","HAVO","Eindexamen","Universiteit","Rijbewijs","Scooter","Eerste baantje","Frikandel","Kroket","Kapsalon","Döner","Bitterballen","H&M","Zara","JD Sports","HEMA","Amsterdam","Rotterdam","Utrecht","Festival","Club"],
    adults: ["Max Verstappen","Formula 1","Red Bull Racing","World Champion","Virgil van Dijk","Frenkie de Jong","Ajax","PSV","Feyenoord","Oranje","Netherlands Football","World Cup","Euro","Martin Garrix","Tiësto","Armin van Buuren","Afrojack","Dutch DJ","EDM","Amsterdam Dance Event","Marco Borsato","André Hazes","Guus Meeuwis","BLØF","Carice van Houten","Famke Janssen","Rutger Hauer","Bitterballen","Stroopwafel","Kroket","Haring","Cheese","Heineken","Amstel","Grolsch","Jenever","Amsterdam","Rotterdam","Utrecht","The Hague","Eindhoven","Canals","Windmills","Tulips","Bicycles","Keukenhof","Anne Frank House","Rijksmuseum","Van Gogh Museum","KLM","Philips","Shell","Albert Heijn"],
    over40: ["Johan Cruyff","Marco van Basten","Ruud Gullit","Frank Rijkaard","World Cup 1974","World Cup 1978","Euro 1988","Total Football","Van Gogh","Rembrandt","Vermeer","André Hazes","Golden Earring","BZN","Doe Maar","André van Duin","Paul de Leeuw","Linda de Mol","Big Brother","GTST","Studio Sport","Bitterballen","Kroket","Haring","Gouda","Edam","Heineken","Amstel","Grolsch","Jenever","DAF","Gulden","Amsterdam","Rotterdam","Keukenhof","Volendam","Sinterklaas","KLM","Philips","Albert Heijn"],
    allAges: ["Amsterdam","Rotterdam","Utrecht","The Hague","Keukenhof","Tulips","Windmills","Canals","Bicycles","Wooden Clogs","Van Gogh","Rembrandt","Anne Frank","Max Verstappen","Johan Cruyff","Virgil van Dijk","Ajax","PSV","Feyenoord","Oranje","Stroopwafel","Cheese","Gouda","Edam","Haring","Bitterballen","Kroket","Heineken","Amstel","Martin Garrix","Tiësto","Armin van Buuren","KLM","Philips","Shell","Albert Heijn","HEMA","King's Day","Sinterklaas","Carnival","Rijksmuseum","Van Gogh Museum","Anne Frank House","Dutch Flag","Orange","Gezellig"]
  }},
  colombia: { name: "Colombia", flag: "🇨🇴", ages: {
    kids: ["Encanto","Mirabel","Bruno","Luisa","Isabela","Casita","Loro","Tucán","Jaguar","Mono","Delfín","Mariposa","Cocodrilo","Tortuga","Fútbol","Natación","Bicicleta","Parque","Playa","Zoo","Arepa","Empanada","Bandeja Paisa","Chocolate","Bocadillo","Helado","Frutas","Mango","Papaya","Navidad","Carnaval","Cumpleaños","Escuela","Profesor","Mamá","Papá","Abuela","Abuelo","Bailar","Cantar","Dibujar","Jugar","Arcoíris","Sol","Luna","Montaña","Río","Selva"],
    tweens: ["Minecraft","Fortnite","Roblox","Free Fire","FIFA","TikTok","YouTube","Instagram","WhatsApp","Netflix","Disney Plus","Encanto","James Rodríguez","Luis Díaz","Selección Colombia","Atlético Nacional","Millonarios","América de Cali","Copa América","Shakira","Maluma","J Balvin","Karol G","Feid","Reggaeton","Arepa","Empanada","Bandeja Paisa","Ajiaco","McDonald's","Hamburguesa","Pizza","Bogotá","Medellín","Cartagena","Cali","Barranquilla","Eje Cafetero","Parque del Café","Panaca","Divercity","Carnaval de Barranquilla","Feria de Cali"],
    teens: ["TikTok","Instagram","YouTube","WhatsApp","Snapchat","Shakira","Maluma","J Balvin","Karol G","Feid","Bad Bunny","Reggaeton","Trap Latino","Vallenato","Cumbia","Festival Estéreo Picnic","Rock al Parque","Netflix","Disney Plus","HBO Max","Luis Díaz","James Rodríguez","Radamel Falcao","Selección Colombia","Atlético Nacional","Millonarios","Copa Libertadores","Bachillerato","Universidad","ICFES","Prom","Licencia de conducir","Primer trabajo","Arepa","Empanada","Ajiaco","Sancocho","Rappi","Uber","Bogotá","Medellín","Cartagena","Cali","Rumba","Discoteca","Aguardiente"],
    adults: ["Shakira","Maluma","J Balvin","Karol G","Carlos Vives","Juanes","Silvestre Dangond","Feid","Gabriel García Márquez","Cien Años de Soledad","Fernando Botero","Sofía Vergara","Juan Pablo Montoya","Nairo Quintana","Egan Bernal","Rigoberto Urán","Tour de France","Ciclismo","Luis Díaz","James Rodríguez","Radamel Falcao","Selección Colombia","Atlético Nacional","Millonarios","Bogotá","Medellín","Cartagena","Cali","Barranquilla","Eje Cafetero","Café Colombiano","Arepa","Bandeja Paisa","Ajiaco","Sancocho","Empanada","Aguardiente","Ron","Cerveza","Club Colombia","Poker","Carnaval de Barranquilla","Feria de las Flores","Salsa","Cumbia","Vallenato","Esmeraldas","Oro","Petróleo"],
    over40: ["Gabriel García Márquez","Cien Años de Soledad","Pablo Escobar","Narcos","Carlos Vives","La Bicicleta","Shakira","Juanes","Joe Arroyo","Diomedes Díaz","Rafael Escalona","Vallenato","Cumbia","Salsa","El Pibe Valderrama","René Higuita","Freddy Rincón","Faustino Asprilla","Andrés Escobar","Copa América 2001","Selección Colombia","Café de Colombia","Juan Valdez","Fernando Botero","Bogotá","Medellín","Cartagena","Eje Cafetero","Bandeja Paisa","Ajiaco","Sancocho","Aguardiente","Poker","Club Colombia","Peso Colombiano","Telecom","Caracol","RCN","Sábados Felices","Carnaval de Barranquilla"],
    allAges: ["Bogotá","Medellín","Cartagena","Cali","Barranquilla","Eje Cafetero","Café Colombiano","Juan Valdez","Shakira","Maluma","J Balvin","Karol G","Carlos Vives","Juanes","Gabriel García Márquez","Fernando Botero","Encanto","Arepa","Empanada","Bandeja Paisa","Ajiaco","Sancocho","Aguardiente","Cumbia","Vallenato","Salsa","Reggaeton","Carnaval de Barranquilla","Feria de las Flores","Luis Díaz","James Rodríguez","Selección Colombia","Ciclismo","Nairo Quintana","Egan Bernal","Esmeraldas","Oro","Café","Loro","Jaguar","Amazonia","Andes","Caribe","Bandera Colombiana","Sombrero Vueltiao"]
  }}
};
